# Generated by Django 3.2.7 on 2021-09-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': 'photos'},
        ),
    ]
