# Generated by Django 3.2.7 on 2021-09-05 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_alter_photos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
