# Generated by Django 3.2.6 on 2021-09-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_auto_20210904_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
