# Generated by Django 3.2.7 on 2021-09-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_auto_20210905_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Cat',
        ),
    ]
