# Generated by Django 3.2.6 on 2021-09-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0007_auto_20210904_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
            ],
        ),
    ]
